<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientsTableSeeder extends Seeder
{
    public function run()
    {
        // Supprimez les données précédentes si nécessaire
        DB::table('clients')->truncate();

        // Créer 10 entreprises avec des données uniques
        $clients = [
            [
                'Nom_Société' => 'Tech Innov',
                'abreviation' => 'TI',
                'Telephone' => '0123456781',
                'Cellulaire' => '0987654311',
                'Email' => 'contact@techinnov.com',
                'Compte_contribuable' => '1234567-A',
                'RCCM' => 'RCCM-001',
                'Direction_1_Nom_et_Prenoms' => 'Jean Dupont',
                'Direction_1_Contact' => '0123456782',
                'Direction_2_Nom_et_Prenoms' => 'Marie Curie',
                'Direction_2_Contact' => '0987654312',
                'Direction_3_Nom_et_Prenoms' => 'Paul Valéry',
                'Direction_3_Contact' => '0771234567',
                'Adresse' => '1 Rue de la Technologie',
                'Commune' => 'Abidjan',
                'Quartier' => 'Plateau',
                'Rue' => 'Avenue des Champs',
                'Zone' => 'Zone A',
                'Autre' => null,
            ],
            [
                'Nom_Société' => 'Global Services',
                'abreviation' => 'GS',
                'Telephone' => '0123456783',
                'Cellulaire' => '0987654313',
                'Email' => 'contact@globalservices.com',
                'Compte_contribuable' => '2345678-B',
                'RCCM' => 'RCCM-002',
                'Direction_1_Nom_et_Prenoms' => 'Alice Martin',
                'Direction_1_Contact' => '0123456784',
                'Direction_2_Nom_et_Prenoms' => 'Bob Leblanc',
                'Direction_2_Contact' => '0987654314',
                'Direction_3_Nom_et_Prenoms' => 'Victor Hugo',
                'Direction_3_Contact' => '0772345678',
                'Adresse' => '2 Avenue des Services',
                'Commune' => 'Yopougon',
                'Quartier' => 'Koutoubou',
                'Rue' => 'Rue de l\'Excellence',
                'Zone' => 'Zone B',
                'Autre' => null,
            ],
            [
                'Nom_Société' => 'Eco-Logistics',
                'abreviation' => 'EL',
                'Telephone' => '0123456785',
                'Cellulaire' => '0987654315',
                'Email' => 'contact@ecologistics.com',
                'Compte_contribuable' => '3456789-C',
                'RCCM' => 'RCCM-003',
                'Direction_1_Nom_et_Prenoms' => 'Léonard Fourni',
                'Direction_1_Contact' => '0123456786',
                'Direction_2_Nom_et_Prenoms' => 'Clara Boucher',
                'Direction_2_Contact' => '0987654316',
                'Direction_3_Nom_et_Prenoms' => 'Emilie Zola',
                'Direction_3_Contact' => '0773456789',
                'Adresse' => '3 Rue de la Logistique',
                'Commune' => 'Cocody',
                'Quartier' => 'Danga',
                'Rue' => 'Boulevard de l\'Environnement',
                'Zone' => 'Zone C',
                'Autre' => null,
            ],
            [
                'Nom_Société' => 'Médic Services',
                'abreviation' => 'MS',
                'Telephone' => '0123456787',
                'Cellulaire' => '0987654317',
                'Email' => 'contact@medicservices.com',
                'Compte_contribuable' => '4567890-D',
                'RCCM' => 'RCCM-004',
                'Direction_1_Nom_et_Prenoms' => 'Sophie GermaGermain',
                'Direction_1_Contact' => '0123456788',
                'Direction_2_Nom_et_Prenoms' => 'Louis Pasteur',
                'Direction_2_Contact' => '0987654318',
                'Direction_3_Nom_et_Prenoms' => 'Nicolas Tesla',
                'Direction_3_Contact' => '0774567890',
                'Adresse' => '4 Boulevard Médical',
                'Commune' => 'Treichville',
                'Quartier' => 'Gokou',
                'Rue' => 'Avenue de la Santé',
                'Zone' => 'Zone D',
                'Autre' => null,
            ],
            [
                'Nom_Société' => 'Innovations BTP',
                'abreviation' => 'IB',
                'Telephone' => '0123456789',
                'Cellulaire' => '0987654319',
                'Email' => 'contact@innovationsbtp.com',
                'Compte_contribuable' => '5678901-E',
                'RCCM' => 'RCCM-005',
                'Direction_1_Nom_et_Prenoms' => 'Claude Monet',
                'Direction_1_Contact' => '0123456790',
                'Direction_2_Nom_et_Prenoms' => 'Henri Matisse',
                'Direction_2_Contact' => '0987654320',
                'Direction_3_Nom_et_Prenoms' => 'Pablo Picasso',
                'Direction_3_Contact' => '0775678901',
                'Adresse' => '5 Rue des Innovations',
                'Commune' => 'Marcory',
                'Quartier' => 'Les Deux Plateaux',
                'Rue' => 'Avenue des Travaux',
                'Zone' => 'Zone E',
                'Autre' => null,
            ],
            [
                'Nom_Société' => 'Digital Creators',
                'abreviation' => 'DC',
                'Telephone' => '0123456701',
                'Cellulaire' => '0987654321',
                'Email' => 'contact@digitalcreators.com',
                'Compte_contribuable' => '6789012-F',
                'RCCM' => 'RCCM-006',
                'Direction_1_Nom_et_Prenoms' => 'Marie Cur',
                'Direction_1_Contact' => '0123456791',
                'Direction_2_Nom_et_Prenoms' => 'Albert Einstein',
                'Direction_2_Contact' => '0987654322',
                'Direction_3_Nom_et_Prenoms' => 'Isaac Newton',
                'Direction_3_Contact' => '0776789012',
                'Adresse' => '6 Avenue du Numérique',
                'Commune' => 'Abidjan',
                'Quartier' => 'Cocody',
                'Rue' => 'Boulevard des Technologies',
                'Zone' => 'Zone F',
                'Autre' => null,
            ],
            [
                'Nom_Société' => 'Smart Solutions',
                'abreviation' => 'SS',
                'Telephone' => '0123456702',
                'Cellulaire' => '0987654323',
                'Email' => 'contact@smartsolutions.com',
                'Compte_contribuable' => '7890123-G',
                'RCCM' => 'RCCM-007',
                'Direction_1_Nom_et_Prenoms' => 'Léonard Fonier',
                'Direction_1_Contact' => '0123456792',
                'Direction_2_Nom_et_Prenoms' => 'Alice Matin',
                'Direction_2_Contact' => '0987654324',
                'Direction_3_Nom_et_Prenoms' => 'Victor Ho',
                'Direction_3_Contact' => '0777890123',
                'Adresse' => '7 Rue des Solutions',
                'Commune' => 'Yopougon',
                'Quartier' => 'Soguy',
                'Rue' => 'Avenue des Innovateurs',
                'Zone' => 'Zone G',
                'Autre' => null,
            ],
            [
                'Nom_Société' => 'Future Builders',
                'abreviation' => 'FB',
                'Telephone' => '0123456703',
                'Cellulaire' => '0987654325',
                'Email' => 'contact@futurebuilders.com',
                'Compte_contribuable' => '8901234-H',
                'RCCM' => 'RCCM-008',
                'Direction_1_Nom_et_Prenoms' => 'Vtor Hugo',
                'Direction_1_Contact' => '0123456793',
                'Direction_2_Nom_et_Prenoms' => 'Clar Boucher',
                'Direction_2_Contact' => '0987654326',
                'Direction_3_Nom_et_Prenoms' => 'Henri Misse',
                'Direction_3_Contact' => '0778901234',
                'Adresse' => '8 Rue des Bâtisseurs',
                'Commune' => 'Treichville',
                'Quartier' => 'Gokou',
                'Rue' => 'Boulevard de la Construction',
                'Zone' => 'Zone H',
                'Autre' => null,
            ],
            [
                'Nom_Société' => 'Logistics Experts',
                'abreviation' => 'LE',
                'Telephone' => '0123456704',
                'Cellulaire' => '0987654327',
                'Email' => 'contact@logisticsexperts.com',
                'Compte_contribuable' => '9012345-I',
                'RCCM' => 'RCCM-009',
                'Direction_1_Nom_et_Prenoms' => 'Nicolas Tela',
                'Direction_1_Contact' => '0123456794',
                'Direction_2_Nom_et_Prenoms' => 'Sophie Grmain',
                'Direction_2_Contact' => '0987654328',
                'Direction_3_Nom_et_Prenoms' => null,
                'Direction_3_Contact' => null,
                'Adresse' => '9 Rue de la Logistique',
                'Commune' => 'Cocody',
                'Quartier' => 'Danga',
                'Rue' => 'Boulevard de l\'Organisation',
                'Zone' => 'Zone I',
                'Autre' => null,
            ],
            [
                'Nom_Société' => 'Market Leaders',
                'abreviation' => 'ML',
                'Telephone' => '0123456705',
                'Cellulaire' => '0987654329',
                'Email' => 'contact@marketleaders.com',
                'Compte_contribuable' => '0123456-J',
                'RCCM' => 'RCCM-010',
                'Direction_1_Nom_et_Prenoms' => 'Claude Mont',
                'Direction_1_Contact' => '0123456795',
                'Direction_2_Nom_et_Prenoms' => 'Emilie Zols',
                'Direction_2_Contact' => '0987654330',
                'Direction_3_Nom_et_Prenoms' => null,
                'Direction_3_Contact' => null,
                'Adresse' => '10 Avenue des Leaders',
                'Commune' => 'Marcory',
                'Quartier' => 'Les Deux Plateaux',
                'Rue' => 'Avenue des Partenaires',
                'Zone' => 'Zone J',
                'Autre' => null,
            ],
        ];

        foreach ($clients as &$client) {
            $client['code_unique'] = $client['Nom_Société'] . '-' . now()->year . '-' . now()->month . '-' . rand(100000, 999999);
        }

        DB::table('clients')->insert($clients);
    }
}
